### PR TITLE
Fix hash_combine_impl to only test for a specific bit width and not f…

### LINKED ISSUE #8: Different hash_combine() output on OSX vs Linux/Windows 64-bit
On macOS, `size_t` and `uint64_t` are different types. Thus, different `hash_combine_impl()` methods get called on 64-bit Linux/Windows vs macOS, which result in different outputs.

```
#include <boost/container_hash/hash.hpp>
#include <iostream>

int main()
{
    std::size_t x = 0, y = 0;
    boost::hash_combine(x, y);
    std::cout << std::hex << x << "\n";
    // Linux/Windows: e6546b64
    // macOS: 9e3779b9
    return 0;
}
```

### PR DESCRIPTION
**Pull request by pdimov**
…or concrete types

Fixes #8.

### CODE REVIEW

File: include/boost/container_hash/hash.hpp [hunk 1]
```diff
@@ -307,52 +308,56 @@ namespace boost
...
 
-        inline void hash_combine_impl(boost::uint64_t& h,
-                boost::uint64_t k)
+        template<> struct hash_combine_impl<64>
         {
-            const boost::uint64_t m = UINT64_C(0xc6a4a7935bd1e995);
-            const int r = 47;
+            inline static boost::uint64_t fn(boost::uint64_t h, boost::uint64_t k)
+            {
+                const boost::uint64_t m = (boost::uint64_t(0xc6a4a793) << 32) + 0x5bd1e995;
```
Comment (e4lam) [inline include/boost/container_hash/hash.hpp:344]: Just curious, why the switch away from `UINT64_C()` here? When I read bit manipulation code I think I still expect to see `|` used rather than `+`.

**Review by e4lam — COMMENTED** [review]
This change didn't make it into boost 1.77 right?

**Comment by pdimov** [comment]
No, it didn't make it into 1.77; it hasn't been merged at all.

UINT64_C still warns in pedantic mode on GCC or Clang (or both; I forget which) because of the long long constant, and it's not possible to disable the warning, because it happens at preprocessing time. Splitting the constant is the only warning-free way I've found.
